apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck-deployment
  labels:
    app: timecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck-fastapi
          image: quay.io/rh_ee_swongpai/fast-localtime-check:lw-217d4d6d9b0e7886ae03b053db2c4f4cd8b104ec
          ports:
            - containerPort: 8000
