apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck-deployment
  labels:
    app: timecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck-fastapi
          image: quay.io/rh_ee_swongpai/fast-localtime-check:lw-fcf51d48d5a7b328f6c0432cd65afbab197d96b1
          ports:
            - containerPort: 8000
