apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck-deployment
  labels:
    app: timecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck-fastapi
          image: quay.io/rh_ee_swongpai/fast-localtime-check:rhhi-bf4b99bb7a3883e40e581d8d1b327f25011d8825
          ports:
            - containerPort: 8000
